name: Deploy

on:
  # 在针对 `main` 分支的推送上运行。如果你
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches: [master]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dump DEV_DB_NAME
        run: echo -n "${{ secrets.REMOTE_HOST }}"
      - name: Dump REMOTE_USERNAME
        run: echo -n "${{ secrets.REMOTE_USERNAME }}"
      - name: Dump REMOTE_PORT
        run: echo -n "${{ secrets.REMOTE_PORT }}"
      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd /opt
            bash deploy.sh
