# 构建 VitePress 站点并将其部署到 GitHub Pages 的示例工作流程
#
name: Deploy VitePress site to Pages

on:
  # 在针对 `main` 分支的推送上运行。如果你
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches: [master]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install PNPM
        run: npm i -g pnpm
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: pnpm install # 或 pnpm install / yarn install / bun install
      - name: Build with VitePress
        run: pnpm docs:build # 或 pnpm docs:build / yarn docs:build / bun run docs:build
      - name: Build with @al-config/vite
        run: pnpm build --pkg @al-config/vite
      - name: Build with @ai-lowcode/utils
        run: pnpm build --pkg @ai-lowcode/utils
      - name: Build with @ai-lowcode/styles
        run: pnpm build --pkg @ai-lowcode/styles
      - name: Build with @ai-lowcode/hooks
        run: pnpm build --pkg @ai-lowcode/hooks
      - name: Build with @ai-lowcode/element-plus
        run: pnpm build --pkg @ai-lowcode/element-plus
      - name: Build with @ai-lowcode/request
        run: pnpm build --pkg @ai-lowcode/request
      - name: Build with @ai-lowcode/designer
        run: pnpm build --pkg @ai-lowcode/designer
      - name: Build with designer
        run: pnpm turbo run build --filter=designer
      - name: remove designer
        run: mkdir dist/designer -p && cp -r app/designer/dist/* dist/designer
      - name: remove docs
        run: cp -r docs/.vitepress/dist/* dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  # 部署工作
  deploy:
    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: docs
        id: deployment
        uses: actions/deploy-pages@v4
